ToyoApps/urls.py
from django.contrib import admin
from django.urls import path, include   # ←, includeを追加
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView

from . import settings

urlpatterns = [
    path('backlog/', include('backlog.urls')),   # ←ここを追加
    path('admin/', admin.site.urls),
    path('file_upload/', include('file_upload.urls')),
    path('slack/', include('slack.urls')),
    path('sft/', include('sft.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sft/urls.py
from django.urls import path

from sft import views

app_name = 'sft'
urlpatterns = [
    # slack
    path('', views.index, name='index'),   # 一覧
    path('user_list/', views.user_list, name='user_list'),   # user一覧
    path('user/<int:pk>/', views.user_edit, name='user_edit'),  # 詳細
    path('user/add/', views.user_edit, name='user_add'),  # 追加
    path('sft_chart/', views.sft_chart, name='sft_chart'),   # シフトチャート
    path('schedule/<int:pk>/', views.schedule_edit, name='schedule_edit'),  # 詳細
    path('schedule/add/', views.schedule_edit, name='schedule_add'),  # 追加
    path('comment/', views.comment_list, name='comment_list'),   # 一覧
    path('department_list/', views.department_list, name='department_list'),  # 一覧
    path('department/<int:pk>/', views.department_edit, name='department_edit'),  # 詳細
    path('department/add/', views.department_edit, name='department_add'),  # 追加
    path('create_user/', views.create_slack_menber, name='create_slack_menber'),   # ユーザー作成
    # path('add_event$', views.add_event, name='add_event'),
    # path('sft_chart/update$', views.update, name='update'),
    # path('sft_chart/remove', views.remove, name='remove'),
]

slack/urls.py
from django.urls import path
from slack import views
from django.contrib.auth import views as auth_views

app_name = 'slack'
urlpatterns = [
    # slack
    path('', views.index, name='index'),   # 一覧
    path('login/', auth_views.LoginView.as_view(template_name='slack/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('status/<int:user_id>/<str:status>/', views.status, name='status'),   # ステータス修正
    path('create_seat/<int:user_id>/', views.create_seat, name='create_seat'),   # 座席を発行する
    path('user_list/', views.user_list, name='user_list'),   # user一覧
    path('user/<int:pk>/', views.user_edit, name='user_edit'),  # 詳細
    path('user/del/<int:pk>/', views.user_del, name='user_del'),  # 削除
    path('comment/', views.comment_list, name='comment_list'),   # 一覧
    path('department_list/', views.department_list, name='department_list'),  # 一覧
    path('department/<int:pk>/', views.department_edit, name='department_edit'),  # 詳細
    path('department/add/', views.department_edit, name='department_add'),  # 詳細
    path('department/del/<int:pk>/', views.department_del, name='department_del'),  # 削除
    path('create_user/', views.create_slack_menber, name='create_slack_menber'),   # ユーザー作成
]

sft/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    """Schedule"""
    STATUS = (
        (10,"仮登録"),
        (20,"確定")
    )
    userId = models.CharField('code', max_length=255)
    start_time =  models.TimeField('startTime', blank=True, null=True)
    end_time = models.TimeField('endTime', blank=True, null=True)
    startDate = models.DateField('startDate', blank=True, null=True)
    comment =  models.TextField('comment', blank=True, null=True, max_length=5000 )
    title = models.CharField('title', blank=True, null=True, max_length=255 )
    status = models.IntegerField('ステータス', choices=STATUS, blank=True, null=True, default=10)

    def __str__(self):
        return self.title

class Users(models.Model):
    """Users"""
    STATUS = (
        (10,'正社員'),
        (20, 'パート'),
        (30, 'アルバイト')
    )
    name = models.CharField('名前', max_length=255)
    user_code = models.CharField('社員コード', max_length=255, null=True, blank=True)
    employment_status = models.IntegerField('雇用形態', choices=STATUS, blank=True, null=True)
    comment = models.TextField('comment', blank=True, null=True, max_length=5000 )

    def __str__(self):
        return self.name

slack/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    """Message"""
    user_code = models.CharField('code', max_length=255)
    post_time =  models.CharField('postTime', max_length=255)
    message = models.TextField('message', max_length=50000, blank=True)
    slack_comment_id = models.CharField('message', max_length=255, blank=True)
    encode_time =  models.DateTimeField('postTimes', blank=True, null=True )

    def __str__(self):
        return self.message

class SlackMember(models.Model):
    """Message"""
    name = models.CharField('名前', max_length=255, null=True, blank=True)
    slack_name =  models.CharField('slack名', max_length=255)
    slack_id = models.CharField('slackId', max_length=255)
    status = models.CharField('ステータス', max_length=255, null=True, blank=True)
    update_time = models.DateTimeField('投稿時間', null=True, blank=True)
    department = models.ForeignKey('Department', verbose_name='部署',on_delete=models.SET_NULL, blank=True, null=True, related_name='department_name')
    account = models.CharField('アカウント', max_length=255, null=True, blank=True)
    flg_seat = models.CharField('座席不要フラグ', max_length=255, null=True, blank=True, default=0)

    def __str__(self):
        return self.name

class Department(models.Model):
    """部署"""
    BRANCH = (
        (10 , '本社'),
        (20 , '滋賀支店'),
        (30 , '舞鶴支店'),
    )

    name = models.CharField('部署名', max_length=255)
    branch = models.IntegerField('支店', choices=BRANCH, blank=True, null=True)

    def __str__(self):
        return self.name

class Events(models.Model):
    """Evens"""
    summary = models.TextField('summary', max_length=5000, blank=True, null=True)
    location = models.CharField('location', max_length=255, null=True, blank=True)
    startDate = models.CharField('startDate', max_length=255, null=True, blank=True)
    endDate = models.CharField('endDate', max_length=255, null=True, blank=True)
    iCalUID = models.TextField('iCalUID', blank=True, null=True, max_length=5000 )
    etag = models.CharField('etag', max_length=255, null=True, blank=True)
    googleEventId = models.CharField('etag', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.summary

class Seat(models.Model):
    """Seats"""
    seat_number = models.CharField('座席番号', max_length=255, null=True, blank=True)
    user_id = models.CharField('社員Id', blank=True, null=True, max_length=255 )
    eventDate = models.DateField('eventDate', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.seat_number

sft/forms.py
from django import forms

from .models import Users, Schedule

class UsersForm(forms.ModelForm):

    class Meta:
        model = Users
        fields = ('name', 'user_code','employment_status', 'comment',)

class SchedulesForm(forms.ModelForm):

    class Meta:
        model = Schedule
        fields = ('title', 'startDate', 'start_time', 'end_time', 'comment', 'status',)

sft/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from .forms import UsersForm, SchedulesForm
from django.db.models import Q

from .models import Users, Schedule

def index(request):
    """TOPメニュー"""
    return render(request,
                  'sft/index.html',  # 使用するテンプレート
                    )  # テンプレートに渡すデータ

def user_list(request):
    """User List"""
    users = Users.objects.all()
    return render(request,
                  'sft/user_list.html',  # 使用するテンプレート
                  {'users': users}, )  # テンプレートに渡すデータ

def user_edit(request, pk=None):
    if pk:  # idがあるとき（編集の時）
        # idで検索して、結果を戻すか、404エラー
        member = get_object_or_404(Users, pk=pk)
    else:  # idが無いとき（新規の時）
        # Memberを作成
        member = Users()

    # POSTの時（新規であれ編集であれ登録ボタンが押されたとき）
    if request.method == 'POST':
        # フォームを生成
        form = UsersForm(request.POST, instance=member)
        if form.is_valid():  # バリデーションがOKなら保存
            member = form.save(commit=False)
            member.save()
            return redirect('sft:user_list')
    else:  # GETの時（フォームを生成）
        form = UsersForm(instance=member)

    # 新規・編集画面を表示
    return render(request, 'sft/member_edit.html', dict(form=form ))

def schedule_edit(request, pk=None):
    if pk:  # idがあるとき（編集の時）
        # idで検索して、結果を戻すか、404エラー
        schedule = get_object_or_404(Schedule, pk=pk)
    else:  # idが無いとき（新規の時）
        # Memberを作成
        schedule = Schedule()

    # POSTの時（新規であれ編集であれ登録ボタンが押されたとき）
    if request.method == 'POST':
        # フォームを生成
        form = SchedulesForm(request.POST, instance=schedule)
        if form.is_valid():  # バリデーションがOKなら保存
            schedule = form.save(commit=False)
            schedule.save()
            return redirect('sft:sft_chart')
    else:  # GETの時（フォームを生成）
        form = SchedulesForm(instance=schedule)
    # 新規・編集画面を表示
    return render(request, 'sft/schedule_edit.html', dict(form=form, id=id))


def sft_chart(request):
    schedules = Schedule.objects.all()
    users = Users.objects.all()
    # 新規・編集画面を表示
    return render(request, 'sft/GanttChart.html', dict(schedules=schedules, users=users ))


def department_list(request):
    """Department List"""
    departments = Department.objects.all()
    return render(request,
                  'slack/department_list.html',  # 使用するテンプレート
                  {'departments': departments}, )  # テンプレートに渡すデータ

def department_edit(request, pk=None):
    if pk:  # idがあるとき（編集の時）
        # idで検索して、結果を戻すか、404エラー
        member = get_object_or_404(Department, pk=pk)
    else:  # idが無いとき（新規の時）
        # Memberを作成
        member = Department()

    # POSTの時（新規であれ編集であれ登録ボタンが押されたとき）
    if request.method == 'POST':
        # フォームを生成
        form = DepartmentForm(request.POST, instance=member)
        if form.is_valid():  # バリデーションがOKなら保存
            member = form.save(commit=False)
            member.save()
            return redirect('slack:department_list')
    else:  # GETの時（フォームを生成）
        form = DepartmentForm(instance=member)
    # 新規・編集画面を表示
    return render(request, 'slack/department_edit.html', dict(form=form, id=id))


def comment_list(request):
    """メッセージの一覧"""
    # salckメッセージ取込
    get_slack();
    # ステータス更新
    update_status();

    departments = Department.objects.all()

    slacks = SlackMember.objects.all()
    keyword = request.GET.get('query')
    key = request.GET.get('key')
    print(key)
    if keyword:
        slacks = slacks.filter(
            Q(name__contains=keyword)
        )
    if key:
        slacks = slacks.filter(
            Q(department_id=key)
        )

    return render(request,
                  'slack/slack_index.html',  # 使用するテンプレート
                  {'slacks': slacks,
                   'departments': departments},)  # テンプレートに渡すデータ

def create_slack_menber(request):
    create_user();
    return HttpResponse('Create User')

def calendar(request):
    all_events = Schedule.objects.all()
    context = {
        "events":all_events,
    }
    return render(request,'GanttChart.html',context)

def add_event(request):
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    title = request.GET.get("title", None)
    resourceId = request.GET.get("resourceId", None)
    print(resourceId)
    event = Schedule(name=str(title), start=start, end=end)
    event.save()
    data = {}
    return JsonResponse(data)


def update(request):
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    title = request.GET.get("title", None)
    id = request.GET.get("id", None)
    event = Schedule.objects.get(id=id)
    event.start = start
    event.end = end
    event.name = title
    event.save()
    data = {}
    return JsonResponse(data)

def remove(request):
    id = request.GET.get("id", None)
    event = Schedule.objects.get(id=id)
    event.delete()
    data = {}
    return JsonResponse(data)

sft/templates/sft/GanttChart.html
{% load i18n static %}
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="utf-8">
		<meta http-equiv='X-UA-Compatible' content='IE=Edge' />
		<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css' />
		<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar-scheduler/1.6.2/scheduler.min.css' />
		<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js'></script>
		<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
		<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js'></script>
		<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar-scheduler/1.6.2/scheduler.min.js'></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/locale/ja.js"></script>
		<script>

			$(function() {

				$('#calendar').fullCalendar({
					schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source',
					defaultDate: '2020-06-03',
					now: '"&~now&"',
					nowIndicator: true,
					editable: true,
					selectable: true,
					selectHelper: true,
					height: 300,
					contentHeight: 300,
					slotDuration: '00:30:00',
					slotLabelInterval: '1:00',
					minTime: '07:00:00',
				    maxTime: '23:00:00',
					resourceAreaWidth: '10%',
					scrollTime: '03:00',
					header: false,
					defaultView: 'timelineDay',
					resourceLabelText: '氏名',

					select: function (start, end, allDay) {
                    var title = prompt("Enter Event Title");
                    if (title) {
                        var start = $.fullCalendar.formatDate(start, "Y-MM-DD HH:mm:ss");
                        var end = $.fullCalendar.formatDate(end, "Y-MM-DD HH:mm:ss");
                        $.ajax({
                            type: "GET",
                            url: 'add_event/',
                            data: {'title': title, 'start': start, 'end': end},
                            dataType: "json",
                            success: function (data) {
                                calendar.fullCalendar('refetchEvents');
                                alert("Added Successfully");
                            },
                            failure: function (data) {
                                alert('There is a problem!!!');
                            }
                        });
                    }
                },
				 eventResize: function (event) {
                    var start = $.fullCalendar.formatDate(event.start, "Y-MM-DD HH:mm:ss");
                    var end = $.fullCalendar.formatDate(event.end, "Y-MM-DD HH:mm:ss");
                    var title = event.title;
                    var id = event.id;
                    var resourceId = event.resouceId;
                    $.ajax({
                        type: "GET",
                        url: '/update',
                        data: {'title': title, 'start': start, 'end': end, 'id': id, 'resourceId': resourceId},
                        dataType: "json",
                        success: function (data) {
                            calendar.fullCalendar('refetchEvents');
                            alert('Event Update');
                        },
                        failure: function (data) {
                            alert('There is a problem!!!');
                        }
                    });
                },
				eventDrop: function (event) {
                    var start = $.fullCalendar.formatDate(event.start, "Y-MM-DD HH:mm:ss");
                    var end = $.fullCalendar.formatDate(event.end, "Y-MM-DD HH:mm:ss");
                    var title = event.title;
                    var id = event.id;
                    var resourceId = event.resouceId;
                    $.ajax({
                        type: "GET",
                        url: '/update',
                        data: {'title': title, 'start': start, 'end': end, 'id': id, 'resourceId': resourceId},
                        dataType: "json",
                        success: function (data) {
                            calendar.fullCalendar('refetchEvents');
                            alert('Event Update');
                        },
                        failure: function (data) {
                            alert('There is a problem!!!');
                        }
                    });
                },

				eventClick: function (event) {
                    if (confirm("Are you sure you want to remove it?")) {
                        var id = event.id;
                        $.ajax({
                            type: "GET",
                            url: '/remove',
                            data: {'id': id},
                            dataType: "json",
                            success: function (data) {
                                calendar.fullCalendar('refetchEvents');
                                alert('Event Removed');
                            },
                            failure: function (data) {
                                alert('There is a problem!!!');
                            }
                        });
                    }
                },

					resources: [
						{% for user in users %}
								{
									'id': '{{user.id }}',
									'title': '{{ user.name }}',
									'building' : 10
								},
							{% endfor %}
					],
                     events: [
                     		{% for schedule in schedules %}
								{
									'id': '{{schedule.id }}',
									'end': '{{ schedule.startDate }}T{{ schedule.endDate }}',
									'start':'{{ schedule.startDate }}T{{ schedule.startDate }}',
									'resourceId':'{{ schedule.userId}}',
									'title':'{{ schedule.title }}'
								},
							{% endfor %}
					 ]

				});

			});

		</script>
		<style>

			body {
				margin: 0;
				padding: 0;
				font-family: Arial;
				font-size: 14px;
			}

			#calendar {
				max-width: 1630px;
				margin: 5px auto;
			}

		</style>

	</head>
	<body style='border:0;padding:0;margin:0;'>
	<div class="TOP">
		<a href="{% url 'sft:index' %}">
			<img src="{% static 'sft/img/smileinit.png' %}" class="img-fluid" width="50pt">
			<img src="{% static 'sft/img/logo.png' %}" class="img-fluid" width="100pt">
		</a>
	</div>
		<div id='calendar'></div>
	</body>
</html>

sft/templates/sft/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'sft/css/bootstrap.min.css' %}">
  <style>
    .btn-square {
      display: inline-block;
      padding: 0.5em 1em;
      text-decoration: none;
      background: #0033CC;/*ボタン色*/
      color: #FFF;
      border-bottom: solid 4px #627295;
      border-radius: 3px;
    }
    .btn-square:active {
      /*ボタンを押したとき*/
      -webkit-transform: translateY(4px);
      transform: translateY(2px);/*下に動く*/
      border-bottom: none;/*線を消す*/
    }
    body{
      font-size : 15px;
    }
    table{
      margin-left: auto;
      margin-right: auto;
      margin-top: 20px;
      text-align: center;
    }
    td{
      width: 1000px;
    }
    th{
      width: 200px;
    }
    .center{
      margin-left: auto;
      margin-right: auto;
    }

  .box {
    display: inline-block; /* インラインブロック要素にする */
  }


.cp_ipselect {
	overflow: hidden;
	width: 90%;
	margin: 2em auto;
	text-align: center;
}
.cp_ipselect select {
	width: 100%;
	padding-right: 1em;
	cursor: pointer;
	text-indent: 0.01px;
	text-overflow: ellipsis;
	border: none;
	outline: none;
	background: transparent;
	background-image: none;
	box-shadow: none;
	-webkit-appearance: none;
	appearance: none;
}
.cp_ipselect select::-ms-expand {
    display: none;
}
.cp_ipselect.cp_sl04 {
	position: relative;
	border-radius: 2px;
	border: 2px solid #000000;
    border-radius: 50px;
	background: #ffffff;
}
.cp_ipselect.cp_sl04::before {
	position: absolute;
	top: 0.8em;
	right: 0.8em;
	width: 0;
	height: 0;
	padding: 0;
	content: '';
	border-left: 6px solid transparent;
	border-right: 6px solid transparent;
	border-top: 6px solid #000000;
	pointer-events: none;
}
.cp_ipselect.cp_sl04 select {
	padding: 8px 38px 8px 8px;
	color: #000000;
}

    .TOP{
      margin-top: 20px;
      margin-bottom: 20px;
    }

  </style>
{% block extra_css %}{% endblock %}
<title>{% block title %}シフト管理{% endblock %}</title>
</head>
<body>
  <div class="container">
  <div class="TOP">
    <a href="{% url 'sft:index' %}">
      <img src="{% static 'sft/img/smileinit.png' %}" class="img-fluid" width="50pt">
      <img src="{% static 'sft/img/logo.png' %}" class="img-fluid" width="100pt">
    </a>
  </div>
    {% block content %}
      {{ content }}å
    {% endblock %}
  </div>
<script src="{% static 'sft/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'sft/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

sft/templates/sft/department_edit.html
{% extends 'slack/base.html' %}

{% block content %}
    <h1>部署詳細</h1>
    <hr>
    <form method="POST" class="post-form">
        {% csrf_token %}
        <div class="center">
            <table>
                <tr>
                    <th>部署名</th>
                    <td>{{ form.name }}</td>
                </tr>
                <tr>
                    <th>支店</th>
                    <td>{{ form.branch }}</td>
                </tr>
            </table>

        </div>

        <button type="submit" class="btn-square box">保存</button>
    </form>
{% endblock %}

sft/templates/sft/department_list.html
{% extends "slack/base.html" %}
{% load i18n static %}
{% block title %}部署マスタ{% endblock title %}

{% block content %}
<a href="{% url 'slack:department_add' %}" class="btn-square box">追加</a>
<div class="row">
  <div>
    <table class="table table-striped table-bordered center">
      <thead>
        <tr>
          <th scope="col">部署名</th>
          <th scope="col">支店</th>
        　<th scope="col">詳細</th>
        </tr>
      </thead>
      <tbody>
        {% for department in departments %}
        <tr>
          <td>{{ department.name }}</td>
          <td>{{ department.get_branch_display }}</td>
            <td><a href="{% url 'slack:department_edit' pk=department.id %}">詳細</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
</div>
{% endblock content %}

sft/templates/sft/index.html
{% extends "sft/base.html" %}
{% load i18n static %}
{% block title %}シフト管理{% endblock title %}

{% block content %}
<div class="row">
  <div>
    <h3 class="mt-4 border-bottom"> シフト管理 </h3>
    <table class="table table-striped table-bordered center">
        <tr>
            <td><a href="{% url 'sft:sft_chart' %}">シフト管理</a></td>
        </tr>
        <tr>
            <td><a href="{% url 'sft:user_list' %}">社員マスタ</a></td>
        </tr>
      </tbody>
    </table>
    </div>
</div>
{% endblock content %}

sft/templates/sft/member_edit.html
{% extends 'sft/base.html' %}

{% block content %}
    <h3 class="mt-4 border-bottom">社員詳細</h3>
    <form method="POST" class="post-form">
        {% csrf_token %}
        <div>
            <table class="center">
                <tr>
                    <th>名前</th>
                    <td>{{ form.name }}</td>
                </tr>
                <tr>
                    <th>社員コード</th>
                    <td>{{ form.user_code }}</td>
                </tr>
                <tr>
                    <th>雇用形態</th>
                    <td>{{ form.employment_status }}</td>
                </tr>
                <tr>
                    <th>備考</th>
                    <td>{{ form.comment }}</td>
                </tr>
            </table>

        </div>
        <button type="submit" class="btn-square box">保存</button>
    </form>
{% endblock %}

sft/templates/sft/slack_index.html
{% extends "slack/base.html" %}
{% load i18n static %}
{% block title %}勤務状況管理{% endblock title %}

{% block content %}
<div class="row">
  <div class="boxContainer">
      <form action="" method="get">
<!--        <p class="box">検索条件 :</p>-->
<!--        <input name="query" value="{{ request.GET.query }}" type="text" placeholder="名前検索" class="box">-->
        <div  class="cp_ipselect cp_sl04 box">
        <select  name="key" value="{{ request.GET.query }}" type="text" placeholder="部署" class="select-wrap select-primary">
            <option value="">部署名</option>
          {% for d in departments %}
            <option value={{ d.id }}>{{ d.name }}</option>
          {% endfor %}
        </select>
        </div>
        </input>
        <button type="submit" class="btn-square box">検索</button>
    </form>
  </div>
  <div>
    <table class="table table-striped table-bordered center">
      <thead>
        <tr>
          <th scope="col">名前</th>
          <th scope="col">部署</th>
          <th scope="col">ステータス</th>
          <th scope="col">投稿時間</th>
        </tr>
      </thead>
      <tbody>
        {% for slack in slacks %}
        <tr>
          <td><a href="{% url 'slack:user_edit' pk=slack.id %}">{{ slack.name }}</a></td>
          <td>{{ slack.department }}</td>
          <td>{{ slack.status }}</td>
          <td>{{ slack.update_time }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
</div>
{% endblock content %}

sft/templates/sft/user_list.html
{% extends "sft/base.html" %}
{% load i18n static %}
{% block title %}社員マスタ{% endblock title %}

{% block content %}
  <a href="{% url 'sft:user_add' %}" class="btn-square box">新規登録</a>
<div class="row">
  <div>
    <table class="table table-striped table-bordered center">
      <thead>
        <tr>
          <th scope="col">社員コード</th>
          <th scope="col">氏名</th>
        　<th scope="col">雇用形態</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <td><a href="{% url 'sft:user_edit' pk=user.id %}">{{ user.user_code }}</a></td>
          <td>{{ user.name }}</td>
          <td>{{ user.get_employment_status_display }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    </div>
</div>
{% endblock content %}